#!/bin/bash
arch_install () 
{ 
    FOLD=~/machine;
    FILE=$FOLD/arch_install.sh;
    vim $FILE;
    cd $FOLD;
    git add $FILE;
    git commit -m "$FILE install mofified";
    git push;
    cd -
}
arch_install "$@"
