#!/bin/bash
machine_install () 
{ 
    FILE=~/machine/install.sh;
    vim $FILE;
    cd $FILE;
    git add $FILE;
    git commit -m "$FILE install mofified";
    git push;
    cd -
}
machine_install "$@"
