#!/usr/bin/bash

NAME={1:-"ArchLinuxARM-aarch64-latest.tar.gz"}

mkfs.vfat /dev/nbd0p1
mkfs.ext4 /dev/nbd0p2
mkdir rootfs
mount /dev/nbd0p2 rootfs
mkdir rootfs/boot
mount /dev/nbd0p1 rootfs/boot 
bsdtar -xpf $NAME -C rootfs
