#!/usr/bin/bash

if [ "$#" -eq 1 ] ; then
    echo "Usage: $0 disk_name"
    exit 1
fi

NAME=$1

modprobe nbd
qemu-nbd --connect=/dev/nbd0 $NAME
sudo fdisk /dev/nbd0 <<EOF
g
n


+400M
t
1
n



w
EOF

