#!/bin/bash
remote_copy () 
{ 
    ITEM=${1:-""};
    USER=${2:-$LOGNAME};
    HOST=${3:-"37.187.180.32"};
    PORT=${4:-"9191"};
    if [ -z "$ITEM" ]; then
        return 1;
    fi;
    sudo -u $USER scp -i /home/$USER/.ssh/id_rsa -P $PORT -r $ITEM $USER@$HOST:$ITEM
}
remote_copy "$@"
