#!/usr/bin/bash

ip tuntap add dev tap0 mode tap user "$USER"
ip link set tap0 up

ip link add name br0 type bridge
ip link set br0 up
ip link set tap0 master br0

ip link set wlan0 master br0
dhclient br0

