#!/usr/bin/bash

DIR=${LOG_CONN_DIR:-"/var/log/tcpd"}
TIME=$(date +"%T")
DATE=$(date +"%y%m%d")
SUB_DIR=${1:-"$(echo $DATE | sed 's/:/_/g')"}
DIR="$DIR/$SUB_DIR"
NAME=${2:-"$DATE-${TIME}-dflt"}.pcap

FILE=$DIR/$NAME

echo "File at $FILE"
if [ "$#" -lt 1 ] ; then
	echo "usage $0 filename"
	echo "File at $FILE"
	exit 1 
fi

mkdir -p $DIR
echo "File at $FILE"

DEVICE=$(ip addr | grep -v DOWN | grep -E "^[0-9]" | awk -F':' '{print $2}' | grep -v lo)
NB_DEVICES="$(echo ${DEVICE} | awk '{print NF}')"

if [ $NB_DEVICES -lt "1" ] ; then
	echo no device
	echo $DEVICE
	exit 1
elif [ $NB_DEVICES -gt "1" ] ; then
	echo several devices, precise it using '$2':
	echo $DEVICE
	exit 1
fi

echo 'DEVICE='$DEVICE
echo 

tcpdump -n >> $FILE
#tcpdump -n -vvv -i $DEVICE >> $FILE

exit 1

